export const metadata = { title: "About — Arcanum" };

export default function AboutPage() {
  return (
    <main>
      <span className="star-mark" aria-hidden>
        ✧
      </span>
      <h1>About</h1>
      <p>
        Arcanum is a small, private instrument for tarot readings — built for
        an invited circle rather than the public. It pairs a rigorously
        independent card draw and carefully sourced esoteric correspondences
        with a single, considered written interpretation.
      </p>
      <p>
        It is deliberately not a chatbot, a social platform, or a journal. It
        asks for as little as possible, remembers less, and treats both the
        tarot tradition and your privacy with the same seriousness. The
        Methodology page describes how a reading is put together; the Privacy
        page describes exactly what is and is not retained.
      </p>
      <p>
        Card imagery is the “Celestial Prototype” deck: original geometric
        presentations generated by the application itself, with each card's
        traditional attributions drawn from documented historical sources.
      </p>
    </main>
  );
}
